from typing import Literal

from pydantic import BaseModel, Field


class FailureAnalysis(BaseModel):
    """
    AI analysis of the test failure.
    """

    failureCategory: Literal[
        "Product Defect",
        "Automation Script Issue",
        "Environment Issue",
        "Infrastructure Issue",
        "Test Data Issue",
        "Configuration Issue",
        "Inconclusive"
    ]

    confidenceScore: int = Field(
        ge=0, #kind of min value
        le=100, #kind of max value
        description="Confidence score between 0 and 100."
    )

    reasoning: str


class DefectReport(BaseModel):
    """
    Defect details generated by AI.
    """

    defectId: str
    title: str
    module: str
    feature: str
    description: str

    stepsToReproduce: list[str]

    expectedResult: str
    actualResult: str

    severity: Literal[
        "Critical",
        "High",
        "Medium",
        "Low"
    ]

    priority: Literal[
        "Critical",
        "High",
        "Medium",
        "Low"
    ]

    environment: str
    browser: str
    operatingSystem: str

    testCaseId: str
    automationTestName: str

    possibleRootCause: str
    supportingEvidence: str
    recommendation: str


class DefectResponse(BaseModel):
    """
    Root object returned by Gemini.
    """

    failureAnalysis: FailureAnalysis
    """
    Generate a defect ONLY if the failure is a Product Defect according to system prompt.
    suppose any automation script issue occure then the defectReport is returning null but rhe failureAnalysis return values like- 
    
    {
    "failureAnalysis": {
        "failureCategory": "Automation Script Issue",
        "confidenceScore": 98,
        "reasoning": "Invalid XPath."
    },

    "defectReport": null
    }
    
    """
    defectReport: DefectReport | None = None 