#this is a manul approach - clling agets and the program is not completed yet this is a kind of poc/understanding purpose, I move top the automatic approach in the same file and commented this manual approach code for reference. 


# import os
# from pathlib import Path

# from dotenv import load_dotenv
# from google import genai
# from google.genai import types


# # ============================================================
# # 1. Load environment variables
# # ============================================================

# load_dotenv()

# API_KEY = os.getenv("GEMINI_API_KEY")
# MODEL = os.getenv("GEMINI_API_MODEL", "gemini-3.5-flash")


# if not API_KEY:
#     raise ValueError("GEMINI_API_KEY is not configured.")


# # ============================================================
# # 2. Create Gemini client
# # ============================================================

# client = genai.Client(api_key=API_KEY)


# # ============================================================
# # 3. TOOL 1: read_user_story()
# # ============================================================
# #
# # This tool reads the user story from a .txt file.
# #
# # ============================================================

# def read_user_story() -> str:
#     """
#     Read the user story from user_story.txt.

#     Returns:
#         The user story text.
#     """

#     file_path = Path("user_story.txt")

#     print("\n========== TOOL: read_user_story ==========")

#     if not file_path.exists():
#         raise FileNotFoundError(
#             f"User story file not found: {file_path}"
#         )

#     user_story = file_path.read_text(
#         encoding="utf-8"
#     ).strip()

#     if not user_story:
#         raise ValueError(
#             "user_story.txt is empty."
#         )

#     print("User story successfully read.")
#     print("============================================")

#     return user_story


# # ============================================================
# # 4. TOOL 2: generate_test_cases()
# # ============================================================
# #
# # IMPORTANT:
# #
# # There are NO hardcoded test cases here.
# #
# # This function sends the user story to Gemini and asks Gemini
# # to generate the test cases.
# # ============================================================

# def generate_test_cases(user_story: str) -> str:
#     """
#     Generate test cases from a user story using Gemini.

#     Args:
#         user_story: The user story used to generate test cases.

#     Returns:
#         Test cases generated by Gemini.
#     """

#     print("\n========== TOOL: generate_test_cases ==========")

#     prompt = """
#             You are an experienced SDET.

#             Analyze the following user story and generate comprehensive
#             software test cases.

#             Include:

#             1. Positive test scenarios
#             2. Negative test scenarios
#             3. Boundary or edge cases where applicable
#             4. Clear test case titles
#             5. Test steps
#             6. Expected results

#             User Story:
#             --------------------
#             {user_story}
#             --------------------

#             Return the test cases in a clear and structured format.
#             """

#     response = client.models.generate_content(
#         model=MODEL,
#         contents=prompt
#     )

#     print("Gemini generated the test cases.")
#     print("================================================")

#     return response.text


# # ============================================================
# # 5. Register our tools
# # ============================================================

# tools = [
#     read_user_story,
#     generate_test_cases
# ]

# # ============================================================
# # 6. User's request to the Agent
# # ============================================================
# #
# # Notice:
# #
# # We are NOT telling Python:
# #
# #   read_user_story()
# #   generate_test_cases()
# #
# # We give the Agent a goal.
# #
# # The Agent decides which tool to use.
# # ============================================================

# user_prompt = """
# Read the user story and generate comprehensive test cases for it.

# First use the read_user_story tool.
# Then use the generate_test_cases tool with the user story
# returned by the first tool.
# """


# # ============================================================
# # 7. Conversation history

# # Key points
# # contents --> Conversation/history sent to Gemini
# # Content -->One message in that conversation
# # role="user" -->This message came from the user
# # parts --> Pieces that make up the message
# # Part.from_text()-->This piece contains text
# # text=user_prompt --> The actual user request

# # ============================================================

# contents = [
#     types.Content(
#         role="user",
#         parts=[
#             types.Part.from_text(
#                 text=user_prompt
#             )
#         ]
#     )
# ]





"""
I would prefer automatyic approach - calling agents automatically
Yes. For the automatic approach, your code becomes much simpler because the Google GenAI Python SDK handles the tool-call cycle for you: 
it detects the model's function call, executes the Python function, sends the result back to the model, 
and continues until it can return the final response. 
Automatic function calling is the default when Python functions are passed directly in tools=[...].

"""
import os
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types


# ============================================================
# 1. Load environment variables
# ============================================================

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")
MODEL = os.getenv("GEMINI_API_MODEL", "gemini-3.5-flash")
if not API_KEY:
    raise ValueError("GEMINI_API_KEY is not configured.")


# ============================================================
# 2. Create Gemini client
# ============================================================

client = genai.Client(api_key=API_KEY)


# ============================================================
# 3. TOOL 1: read_user_story()
# ============================================================
#
# This tool reads the user story from a .txt file.
#
# There is NO hardcoded user story here.
# ============================================================

def read_user_story() -> str:
    """
    Read the user story from user_story.txt.

    Returns:
        The user story text.
    """

    print("\n========== TOOL: read_user_story ==========")

    file_path = Path("user_story.txt")

    if not file_path.exists():
        raise FileNotFoundError(
            f"User story file not found: {file_path}"
        )

    user_story = file_path.read_text(
        encoding="utf-8"
    ).strip()

    if not user_story:
        raise ValueError(
            "user_story.txt is empty."
        )

    print("User story successfully read.")
    print("============================================")

    return user_story


# ============================================================
# 4. TOOL 2: generate_test_cases()
# ============================================================
#
# IMPORTANT:
#
# There are NO hardcoded test cases.
#
# This function receives the REAL user story returned by
# read_user_story() and sends it to Gemini.
#
# Gemini generates the actual test cases.
# ============================================================

def generate_test_cases(user_story: str) -> str:
    """
    Generate comprehensive test cases from a user story.

    Args:
        user_story: The user story for which test cases
                    should be generated.

    Returns:
        Test cases generated by Gemini.
    """

    print("\n========== TOOL: generate_test_cases ==========")

    prompt = f"""
You are an experienced SDET.

Your ONLY task is to generate test cases from the EXACT
user story provided below.

IMPORTANT RULES:
1. Use ONLY the supplied user story.
2. Do NOT invent another user story.
3. Do NOT use examples from previous conversations.
4. Do NOT introduce unrelated features.
5. Every test case must be directly traceable to the user story.
6. Generate positive, negative, boundary, and edge cases only
   when they are relevant to this user story.
7. Do not add additional test suites unrelated to the user story.

USER STORY
==================================================
{user_story}
==================================================

Return only the test cases for the above user story
"""

    response = client.models.generate_content(
    model=MODEL,
    contents=prompt,
    config=types.GenerateContentConfig(
        temperature=0.2,
        max_output_tokens=4000
    )
)

    print("Gemini generated the test cases.")
    print("================================================")

    return response.text


# ============================================================
# 5. Register both Python functions as tools
# ============================================================
#
# We simply give the functions to the SDK.
#
# The SDK automatically creates the necessary tool
# declarations from the function signatures/docstrings.
#
# We DO NOT disable automatic function calling.
# ============================================================

tools = [
    read_user_story,
    generate_test_cases
]


# ============================================================
# 6. Give the Agent its goal
# ============================================================
#
# IMPORTANT:
#
# We don't manually call:
#
#     read_user_story()
#     generate_test_cases()
#
# We only give the Agent a goal.
#
# Gemini decides which tool to call and when.
# ============================================================

user_prompt = """
Read the user story from the available user story file
and generate comprehensive test cases.

Follow this workflow:

1. First use the read_user_story tool.
2. After receiving the user story, use the
   generate_test_cases tool.
3. Return the generated test cases to the user.
"""


# ============================================================
# 7. Automatic Agent execution
# ============================================================
#
# The SDK handles:
#
# Gemini decides
#       ↓
# Tool call
#       ↓
# SDK executes Python function
#       ↓
# Tool result sent back to Gemini
#       ↓
# Gemini decides again
#       ↓
# Another tool if necessary
#       ↓
# Final response
#
# We do NOT need:
#
#     while True
#     response.function_calls
#     call.name
#     call.args
#     from_function_response()
#
# because automatic function calling handles these steps.
# ============================================================
system_instruction="""
You are a QA testing agent.

Your workflow is:

1. Use read_user_story first.
2. Use the returned user story as input to
   generate_test_cases.
3. Return the generated test cases.

Do not invent a user story.
Do not generate test cases before reading the user story.
"""
response = client.models.generate_content(
    model=MODEL,
    contents=user_prompt,
    config=types.GenerateContentConfig(
        tools=tools,
        system_instruction=system_instruction,
        temperature=0.2,
        max_output_tokens=1000
    )
)



# ============================================================
# 8. Final response
# ============================================================
#
# By this point the SDK has already handled the tool calls.
# response.text contains the final answer from Gemini.
# ============================================================

print("\n========== FINAL AGENT RESPONSE ==========")

print(response.text)

print("==========================================")

